name: Build/release

on: 
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout git
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: install deps
        run: npm ci

      - name: build
        run: npm run make
        
      - name: zip
        run: |
          powershell Compress-Archive -Path out\* -DestinationPath BasicTodo.zip

      - name: upload build
        uses: softprops/action-gh-release@v2
        with:
          files: BasicTodo.zip
