name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout git
        uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v1

      - name: build da app
        uses: yinxulai/actions-electron-forge@0.05
